Vagrant.configure("2") do |config|
 config.vm.box = "bento/ubuntu-20.04"
 config.vm.network "public_network"
 config.vm.provision "shell", inline: <<-SHELL
   sudo rm -rf /var/node_exporter
   sudo mkdir /var/node_exporter
   sudo tar xvf /vagrant/node_exporter-1.2.2.linux-amd64.tar -C /var/node_exporter
   sudo cp /vagrant/node_exporter.service /usr/lib/systemd/system/node_exporter.service
   sudo systemctl daemon-reload

   sudo systemctl enable node_exporter --collector.cpu
   sudo systemctl status node_exporter

   SHELL
end