version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./dumps/test_dump.sql:/test_dump.sql
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080